#!/bin/bash
DIR=/opt/thermiqcom

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
  cd $DIR
  NODE_ENV=production nohup "$NODE" "$DIR/main.js" 1>>"$DIR/thermiqcom.log" 2>&1 &
  echo $! > "/var/run/thermiqcom.pid"
}

function stop_app {
  kill `cat /var/run/thermiqcom.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: thermiqcom {start|stop}" ;;
esac
exit 0
